//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework18.EntityFrame
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class EntityFrameworkDbEntities : DbContext
    {
        public EntityFrameworkDbEntities()
            : base("name=EntityFrameworkDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
    }
}
